### ISSUE TITLE
Unrelated Question About MDN Edit

### ISSUE THREAD

**Issue by boblauer** [1337micro/obliterate-chrome-cache#1]
I noticed you made this edit:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes$compare?from=1062202&to=1066350

I was wondering why you did so.  Without that conditional, `[NaN].includes(NaN)` incorrectly evaluates to `false`.

**Comment by boblauer** [comment]
Oh yeah, and sorry to open an issue on a random repo, it's just the only method I had to contact you.

**Comment by 1337micro** [comment]
Yes, I realised yesterday that I shouldn't have removed that condition and
was going to edit it.

However the other edits are needed as far as I know. My linter was
complaining about not specifying the radix, and the mdn documentation
suggests to always specify it as well
